name: Generate Snake

on:
  schedule: # run every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manual run

permissions:
  contents: write  # ✅ allow pushing to branches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Kishalay15
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output   # ✅ creates if doesn’t exist
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
